config/routes.rb
DKESite::Application.routes.draw do
  root 'chapter/public_pages#home'

  get 'rush' => 'rush#index'

  match '/login' , to: 'chapter/public_pages#home' , via: :post
  match '/success' , to: 'application#success' , via: :get
  match '/loggedout' , to: 'application#loggedout' , via: :get
  
  match 'ch_passwd' , to: 'users#ch_passwd' , via: :get
  match 'ch_passwd' , to: 'users#set_passwd' , via: :patch
  
  scope '/users' do
    match '/add_pledges' , to: 'users#add_pledges' , via: :get
    match '/add_pledges' , to: 'users#create_pledges' , via: :post
    match '/query' , to: 'users#query' , via: :post
    match '/kerberos', to: 'users#kerberos' , via: :post
    match '/filter', to: 'users#filter' , via: :post
  end
  match '/users' , to: 'users#update_groups', via: :put
  resources :users
  
  resources :audit_trail
  
  match 'summer_housing', to: 'summer_housing#summer_housing', via: :get
  match 'summer_housing/edit', to: 'summer_housing#summer_housing_edit', via: :get
  resources :summer_housing, path: "/summer_housing_application", as: "summer_apps"
  
  scope module: 'chapter' do
    resources :brothers
    
    match '/house', to: 'residences#house', via: :get
    match '/tour', to: 'residences#tour', via: :get
    scope '/residences' do 
      match '/room_picks', to: 'residences#room_picks', via: :get
      match '/room_picks', to: 'residences#mass_update', via: :post
    end
    resources :residences
    
    scope '/officers'  do
      match '/mass_update', to: 'officers#mass_edit', via: :get
      match '/mass_update', to: 'officers#mass_update', via: :post
      match '/update_contacts', to: 'officers#update_contacts', via: :post
    end
    
    match '/point_breakdown', to: 'house_points#full_breakdown', via: :get
    match 'house_points/reset', to: 'house_points#backup_and_clear', via: :post
    resources :officers do
      resources :house_points, shallow: true
    end
    
    match 'add_bible' , to: 'bibles#add_bible' , via: :get
    match 'add_bible' , to: 'bibles#new_bible' , via: :post
    match 'upload_bible' , to: 'bibles#upload_bible' , via: :post
  end
  
  namespace :backup do
    resources :house_point_tables
  end
  

end

app/models/chapter.rb
module Chapter
  def self.table_name_prefix
    'chapter_'
  end
  
  def self.gen_chapter_roles
    chapters = ["I am not a brother"]
    wikipg = Nokogiri::HTML(open('https://en.wikipedia.org/wiki/List_of_Delta_Kappa_Epsilon_chapters'))
    roles = wikipg.css('table').css('tr')
    roles.each do | chapter |
      info = chapter.text.split("\n")
      if info[4] == "Yes"
        chapters << "#{info[2]} - #{info[1]}"
      end
    end
    return chapters
  end
end

app/controllers/chapter/bibles_controller.rb
class Chapter::BiblesController < AuthenticationController
  
  ###### Used for users uploading bibles  ######
  
  def add_bible
    @new_bible = Chapter::Bible.new
  end
  
  def new_bible
    @new_bible = Chapter::Bible.new(new_bible_params)
    render "add_bible" unless @new_bible.valid?
  end
  
  def upload_bible
    @new_bible = Chapter::Bible.new(new_bible_params)
    @new_bible.uname = @me.uname
    if !@new_bible.valid?
      render "add_bible"
    elsif !@new_bible.create(uploaded_file)
      render "new_bible"
    else
      flash[:success] = "Bible uploaded successfully.  Awaiting confirmation from Broporn"
      redirect_to root_url
    end
  end
  
  
 private
 
 def new_bible_params
   return params.require(:chapter_bible).permit(:class_num,:year,:semester)
 end
 
 def uploaded_file
   return params.require(:chapter_bible).permit(:material)
 end
  
end

app/controllers/chapter/brothers_controller.rb
class Chapter::BrothersController < AuthenticationController
  skip_before_action :logged_in, only: [:index, :show]
  skip_before_action :checks, only: [:update]
  before_action :correct_user, only: [:edit, :update]
  before_action :broporn_permissions, only: [:destroy]
  
  def create
    @brother = User::Brother.new(params)
    if @brother.valid?
      @brother.save
      flash[:success] = "Information updated"
      check_redirect(params[:user_brother][:dke_info], "#{brothers_path}/#{@brother.id}")
    else
      render 'new'
    end
  end
  
  def destroy
    @brother = User::Brother.find(params[:id])
    @brother.destroy
    flash[:success] = "Brother Information for #{@brother.full_name} deleted"
    redirect_to brothers_path
  end
  
  def edit
    @brother = User::Brother.find(params[:id])
  end
  
  def index
    @brothers = User::Brother.get_indexes
  end
  
  def new
    @brother = User::Brother.new
    @brother.user_id = params[:user_id]
    @brother.dke_info.big_id = params[:big_id]
    @brother.dke_info.little_ids = [params[:little_id]]
  end
  
  def show
    @brother = User::Brother.find(params[:id])
  end
  
  def update
    @brother = User::Brother.find(params[:id])
    if @brother.update_attributes(params)
      flash[:success] = "Information updated"
      if @me.status == 0
        @me.set_status(1)
      end
      check_redirect(params[:user_brother][:dke_info], brother_url)
    else
      render 'edit'
    end
  end
  
 private
 
  def check_redirect(params, redirect_path)
    if params[:big_id] == "new"
      redirect_to new_brother_path + "?little_id=" + @brother.dke_info.id.to_s
    elsif !params[:little_ids].nil?
      if params[:little_ids].include?("new")
        redirect_to new_brother_path + "?big_id=" + @brother.dke_info.id.to_s
      else
        redirect_to redirect_path
      end
    else
      redirect_to redirect_path
    end
  end
  
  def correct_user
    unless @me.is_brother?(params[:id])
      flash[:error] = "You do not have acess to this page"
      redirect_to brother_url
    end
  end
  
end

app/controllers/chapter/house_points_controller.rb
class Chapter::HousePointsController < AuthenticationController
  before_action :assigns_points, only: :index
  before_action :officer_permission, only: [:new, :create]
  before_action :entry_permission, only: [:edit, :update, :destroy]
  before_action ->{holds?(["beta"])}, only: :backup_and_clear
  
  def backup_and_clear
    if Backup::HousePointTable.clear_and_backup
      flash[:success] = "House Points entries cleared"
    else
      flash[:error] = "House Points table is currently empty"
    end
    redirect_to officer_house_points_path(1)
  end
  
  def full_breakdown
    @officers = Chapter::Officer.where(assign_points: true).order(position: :asc)
    @breakdown = []
    User::Brother.name_dke_info_id_map(true).each do | year, brothers |
      brothers.each do | brother |
        if brother[1].is_a? Integer
          dke_info = User::Brother::DkeInfo.find(brother[1])
          yr = dke_info.p_class - User::Brother::DkeInfo.cur_p_class + 3
          @breakdown << {id: dke_info.brother_id,
                        name: brother[0],
                        year: dke_info.brother.mit_info.year,
                        y_order: (yr > 0)?(4 - yr):yr,
                        total: dke_info.house_point_total,
                        points: dke_info.house_point_total_breakdown}
        end
      end
    end
    @breakdown.sort_by!{ |a| [0-a[:y_order], 0-a[:total], a[:name]]}
  end
  
  def index
    @officer = Chapter::Officer.find(params[:officer_id])
    @officer_breakdown = @officer.point_entry_breakdown
  end
  
  def new
    @brothers = User::Brother.name_dke_info_id_map(true)
    @entry = Chapter::HousePoint.new
  end
  
  def create
    @entry = Chapter::HousePoint.new(point_entry_params(params))
    @entry.officer_id = @officer.id
    @entry.date = Date.today
    if @entry.valid?
      @entry.save
      redirect_to officer_house_points_path(@officer.id)
    else
      @brothers = User::Brother.name_dke_info_id_map(true)
      render "new"
    end
  end
  
  def edit
    @brothers = User::Brother.name_dke_info_id_map(true)
    @entry = Chapter::HousePoint.find(params[:id])
  end
  
  def update
    @entry = Chapter::HousePoint.find(params[:id])
    if @entry.update_attributes(point_entry_params(params))
      redirect_to officer_house_points_path(@officer.id)
    else
      @brothers = User::Brother.name_dke_info_id_map(true)
      render "edit"
    end
  end
  
  def destroy
    @entry = Chapter::HousePoint.find(params[:id])
    @entry.destroy
    redirect_to officer_house_points_path(@officer.id)
  end
  
 private
 
 def assigns_points
    @officer = Chapter::Officer.find(params[:officer_id])
    unless @officer.assign_points 
      redirect_to main_app.root_url
    end
  end
 
  def officer_permission
    @officer = Chapter::Officer.find(params[:officer_id])
    unless @officer.assign_points && @me.officer?(@officer.name)
      redirect_to main_app.root_url
    end
  end
  
  def entry_permission
    entry = Chapter::HousePoint.find(params[:id])
    @officer = entry.officer
    unless @officer.assign_points && @me.officer?(@officer.name)
      redirect_to main_app.root_url
    end
  end
  
  def point_entry_params(params)
    return params.require(:chapter_house_point).permit(:dke_info_id, :value, :comment)
  end
  
end

app/controllers/chapter/officers_controller.rb
class Chapter::OfficersController < AuthenticationController
  before_action ->{holds?(["beta", "sigma"])}
  
  def create
    @officer = Chapter::Officer.new(officer_params(params))
    if @officer.valid?
      @officer.save
      flash[:success] = "Officer created"
      redirect_to officers_path
    else
      render 'new'
    end
  end
  
  def destroy
    @officer = Chapter::Officer.find(params[:id])
    @officer.destroy
    flash[:success] = "Officer destroyed"
    redirect_to officers_path
  end
  
  def edit
    @officer = Chapter::Officer.find(params[:id])
  end
  
  def index
    @officers = Chapter::Officer.list_all
  end
  
  def mass_edit
    @officers = Chapter::Officer.select("id, name, title, position, dke_info_id").order("position")
    @brothers = User::Brother.name_dke_info_id_map
  end
  
  def mass_update
    Chapter::Officer.mass_update(params.require(:officers))
    flash[:success] = "Officers updated"
    redirect_to officers_path
    
  end
  
  def new
    @officer = Chapter::Officer.new
  end
  
  def update
    @officer = Chapter::Officer.find(params[:id])
    if @officer.update_attributes(officer_params(params))
      flash[:success] = "Officer has been updated"
      redirect_to officers_path
    else
      render 'edit'
    end
  end
  
  def update_contacts
     if Chapter::Officer.update_contacts(update_contacts_params(params))
       flash[:success] = "Contacts Updated"
     end
     redirect_to officers_url
  end
  
 private
 
 def officer_params(params)
   return params.require(:chapter_officer).permit(:name, :title, :dke_info_id, :assign_points, :disp, :contact, :email)
 end
 
  def update_contacts_params(params)
    return params.require(:officer)
  end
  
end

app/controllers/chapter/public_pages_controller.rb
class Chapter::PublicPagesController < ApplicationController
  before_action :correct_user , only: [:edit,:update]
  
  def contact
    @officers = Chapter::Officer.contact_info
  end
  
  def edit
    @content = Chapter::PublicPage.find_by(pname: params[:id])
  end
  
  def home
    if @me.group?("dkepledge")
      render "chapter/home"
    end
  end
  
  def show
    @content = Chapter::PublicPage.find_by(pname: params[:id])
  end
  
  def update
    @content = Chapter::PublicPage.find_by(pname: params[:id])
    if @content.update(update_page_params)
      redirect_to "#{public_pages_path}#{params[:id]}"
    else
      render "edit"
    end
  end
  
 private
 
  def update_page_params
    params.require(:chapter_public_page).permit(:title,:content)
  end
  
  def correct_user
    page = Chapter::PublicPage.find_by(pname: params[:id])
    unless page.can_edit?(@me)
      flash[:error] = "You do not have acess to this page"
      redirect_to "#{root_url}#{params[:id]}"
    end
  end
  
end

app/helpers/chapter/bibles_helper.rb
module Chapter::BiblesHelper
end

app/helpers/chapter/brothers_helper.rb
module Chapter::BrothersHelper
  
  ############ edit.html.erb ###################
  
  #Returns button for deleting a user
  def brother_info_delete
    return link_to("Delete" , 
            brother_path , 
            method: :delete, 
            data: { confirm: "Are you sure you would like to delete #{@brother.full_name}?" },
            :class => "btn")
  end
  
  ############ edit.html.erb & new.html.erb ###################
  
  #Generates select boxes for big brother information
  #@param f_dke: form object for user::brother::dke_info
  #@param dke_info: dke_info instance for selected user
  def big_select(f_dke, dke_info)
    big = (dke_info.nil?)?nil:dke_info.big
    brother_list = User::Brother.name_dke_info_id_map
    brother_list[""] << ["New Brother", "new"]
    big_options = grouped_options_for_select(brother_list, selected=dke_info.big_id)
    return f_dke.select(:big_id, big_options, {}, class:"chosen-select")
  end
  
  #Return length of littles array if dke_info is not nil, otherwise 0
  #@param dke_info: dke_info instance for selected user
  def little_num(dke_info)
    return 1 if dke_info.nil?
    return [dke_info.littles.length, 1].max
  end
  
  #Generates div for all little brothers for a given user
  #@param dke_info: dke_info instance for selected user
  def little_select_div(dke_info)
    little_ids = (dke_info.nil?)?[]:dke_info.little_ids
    if little_ids.length == 0
      return little_select(nil,"0")
    else
      out = "".html_safe
      for i in 0..(little_ids.length-1)
        out += little_select(little_ids[i], i.to_s)
      end
      return out
    end
  end
  
  #Generates select boxes for little brother information
  #@param little: dke_info instance for little brother
  #@param tag: string (should only have values: __n, or integer >= 0
  def little_select(little_id, tag)
    brother_list = User::Brother.name_dke_info_id_map
    brother_list[""] << ["New Brother", "new"]
    out = '<div class="bl-label">Little Brother: '.html_safe
    name = "user_brother[dke_info][little_ids][#{tag}]"
    if little_id.nil?
      little_options = grouped_options_for_select(brother_list)
      if tag == "__n"
        out += select_tag(name , little_options, id: "select_little#{tag}")
      else
        out += select_tag(name, little_options, class:"chosen-select", id: "select_little#{tag}")
      end
    else
      little_options = grouped_options_for_select(brother_list, selected: little_id)
      out += select_tag(name, little_options, class:"chosen-select", id: "select_little#{tag}")
    end
    out += "</div>".html_safe
    return out
  end
  
  ############ show.html.erb ###################
  #Returns link to big brother information
  def big_link(big)
    return link_to(big.brother.full_name , "#{brothers_path}/#{big.brother_id}")
  end
  
  #Returns links to little brother information
  def little_links(littles)
    result = []
    littles.each do | little |
        result << link_to(little.brother.full_name , "#{brothers_path}/#{little.brother_id}")
    end
    return result.join(', ').html_safe
  end
  
  #Returns link to residence information
  def room_link(room)
      return link_to(room.name, "#{residences_path}/#{room.id}")
  end
  
  #Returns positions user holds
  def get_positions(positions)
    result = []
    positions.each do | pos |
      result << pos.title
    end
    return result.join(', ').html_safe
  end
  ########################################################################
    
end

app/helpers/chapter/house_points_helper.rb
module Chapter::HousePointsHelper
  
  def humanize(date)
    return date.strftime("%m/%e/%y")
  end
  
  def brother_total(entries)
    total = 0
    entries.each do | entry |
      total += entry.value
    end
    return total
  end
  
  def delete_text(brother, entry)
    output = "Are you sure you want to delete this entry?\n"
    output += "*#{brother[:first]} #{brother[:last]}: #{entry.value} ~ #{entry.comment}" 
    return output
  end
  
end

app/helpers/chapter/officers_helper.rb
module Chapter::OfficersHelper
  
  ############ edit.html.erb & new.html.erb ###################
  
  #Generates select boxes for big brother information
  #@param f_dke: form object for user::brother::dke_info
  #@param dke_info: dke_info instance for selected user
  def officer_select(form, dke_info_id)
    brother_list = User::Brother.name_dke_info_id_map
    big_options = grouped_options_for_select(brother_list, selected=dke_info_id)
    return form.select(:dke_info_id, big_options, {}, class:"chosen-select")
  end
  
end

app/helpers/chapter/public_pages_helper.rb
module Chapter::PublicPagesHelper
end

app/helpers/chapter/residences_helper.rb
module Chapter::ResidencesHelper
  
  #Method for keeping trach of when to insert <tr> and </tr> tags in index.html.erb
  def counter(inc)
    @counter = 0 if @counter.nil?
    @counter += inc
    return @counter
  end
  
  #Returns a string containing all of the occupants of room
  def get_occupants(room)
    results = []
    room.occupants.each do | occupant |
      results << link_to(occupant.brother.full_name , "#{brothers_path}/#{occupant.brother.id}")
    end
    return results.join(", ").html_safe
  end
  
  #Returns occuupan select fields for a given room
  #@param capacity: int
  #@param occupant_ids: array (ex. [id1, id2, ...])
  #@param name: (optional) string, default: "occupant"
  def occupant_fields(capacity, occupant_ids, name = "occupants")
    brother_list = User::Brother.name_dke_info_id_map
    out = "".html_safe
    for i in 0..capacity-1
      if i < occupant_ids.length
        occupant_options = grouped_options_for_select(brother_list, selected=occupant_ids[i])
      else
        occupant_options = grouped_options_for_select(brother_list)
      end
      out += select_tag("chapter_residence[#{name}][#{i}]", occupant_options, class:"chosen-select") + "<br>".html_safe
    end
    return out
  end
  
end

app/views/chapter/officers/edit.html.erb
<% provide(:title , 'Chapter Officers - Edit Position')%>

<div class="row">
	<div class="span12" align="left">
		<h3>Edit Position</h3>
	</div>
	<div class="span6 offset4" align="left" style="font-weight:bold;">
	  <%= render_errors(@officer)%>
	  <%= form_for(@officer, options={url: "#{officer_path}#update"}) do |pos| %>
		Name: <%= pos.text_field :name%><br>
		Title: <%= pos.text_field :title%><br>
		Current Holder: <%= officer_select(pos, @officer.dke_info_id)%><br><br>
		Email: <%= pos.text_field :email%><br>
		Can assign points: 
		  <%= pos.radio_button( :assign_points, 1, checked: @officer.assign_points)%>Yes
		  <%= pos.radio_button( :assign_points, 0, checked: !@officer.assign_points)%>No<br><br>
		Display on contacts Page: 
		  <%= pos.radio_button( :disp, 1, checked: @officer.disp)%>Yes
		  <%= pos.radio_button( :disp, 0, checked: !@officer.disp)%>No<br><br>
		Contact For: <%= pos.text_area :contact%><br>
		
		<%= pos.submit "Save Changes", class: "btn btn-primary" %>
		<%= link_to("Delete Position" , officer_path , method: :delete, 
					data: { confirm: "Are you sure you would like to delete #{@officer.title}?" }, :class => "btn")%>
	  <%end%>
	</div>
</div>

app/views/chapter/officers/index.html.erb
<% provide(:title , 'Chapter Officers')%>

<div class="row">
	<div class="span12" align="left">
		<h3>
			Chapter Officers
			<div class="btn-group pull-right">
				<%= link_to "Update Officers" , "#{mass_update_path}"  , :class => "btn"%>
				<%= link_to "Add Position" , new_officer_path  , :class => "btn"%>
			</div>
		</h3>
	</div>
	<div class="span12">
	  <%= form_tag update_contacts_url, class: "update_contacts", method: :post do%>
	   <div class="row">
		<ul id="sortable" class="ui-sortable">
		  <% @officers.each do | officer |%>
			<li class="ui-sortable-handle span6" id="<%= officer[:id]%>">
				<b><%= link_to officer[:title], "#{officers_path}/#{officer[:id]}/edit"%>:</b>
				<%= "#{officer[:full_name]} '#{officer[:year]}"%>
				<br><b>Contact For:</b> <%= officer[:contact]%>
				<br><b>Displayed:</b>&nbsp;
				<%= hidden_field_tag("officer[#{officer[:id]}][position]")%>
				<%= radio_button_tag("officer[#{officer[:id]}][disp]", "1", officer[:disp], {disabled: officer[:contact].blank?}) %>Yes&nbsp;
				<%= radio_button_tag("officer[#{officer[:id]}][disp]", "0", !officer[:disp], {disabled: officer[:contact].blank?}) %>No
			</li>
		  <% end %>
		</ul>
	   </div>
	   <%= submit_tag "Update Changes", class: "pull-right btn btn-primary"%>
	  <% end %>
	</div>
</div>
<script type="text/javascript">
	$(document).ready( function() {
		$( "#sortable" ).sortable({ tolerance: "pointer" });
		$( "#sortable" ).disableSelection();
	});
</script>

app/views/chapter/officers/mass_edit.html.erb
<% provide(:title , 'Chapter Officers - Update')%>

<div class="row">
	<div class="span12" align="left">
		<h3>Update Chapter Officers</h3>
	</div>
	<div class="span8" align="right">
	<%= form_tag mass_update_url, method: :post do%>
	  <% @officers.each do |pos|%>
	    <br><%= "#{pos.title} (#{pos.name})"%>:
	  	<%= select_tag( "officers[#{pos.id}]", grouped_options_for_select(@brothers, selected: pos.dke_info_id), class:"chosen-select")%>
	  <%end%>
	  <br><%= submit_tag "Update Positions", class: "btn btn-primary chosen-container"%>
	<%end%>
	</div>
</div>

<script>
	$( document ).ready(function() {
		$(".chosen-select").chosen({allow_single_deselect: true });
	});
</script>

app/views/chapter/officers/new.html.erb
<% provide(:title , 'Chapter Officers - Add Position')%>

<div class="row">
	<div class="span12" align="left">
		<h3>Add Position</h3>
	</div>
	<div class="span6 offset4" align="left">
	  <%= render_errors(@officer)%>
	  <%= form_for(@officer, options={url: "#{officers_path}#create"}) do |pos| %>
		Name: <%= pos.text_field :name%><br>
		Title: <%= pos.text_field :title%><br>
		Current Holder: <%= officer_select(pos, @officer.dke_info_id)%><br><br>
		Email: <%= pos.text_field :email%><br>
		Can assign points: 
		  <%= pos.radio_button( :assign_points, 1, checked: @officer.assign_points)%>Yes
		  <%= pos.radio_button( :assign_points, 0, checked: !@officer.assign_points)%>No<br><br>
		Display on contacts Page: 
		  <%= pos.radio_button( :disp, 1, checked: @officer.disp)%>Yes
		  <%= pos.radio_button( :disp, 0, checked: !@officer.disp)%>No<br><br>
		Contact For: <%= pos.text_area :contact%><br>
		
		<%= pos.submit "Add Position", class: "btn btn-primary" %>
	  <%end%>
	</div>
</div>