config/routes.rb
DKESite::Application.routes.draw do
  root 'chapter/public_pages#home'

  get 'rush' => 'rush#index'

  match '/login' , to: 'chapter/public_pages#home' , via: :post
  match '/success' , to: 'application#success' , via: :get
  match '/loggedout' , to: 'application#loggedout' , via: :get
  
  match 'ch_passwd' , to: 'users#ch_passwd' , via: :get
  match 'ch_passwd' , to: 'users#set_passwd' , via: :patch
  
  scope '/users' do
    match '/add_pledges' , to: 'users#add_pledges' , via: :get
    match '/add_pledges' , to: 'users#create_pledges' , via: :post
    match '/query' , to: 'users#query' , via: :post
    match '/kerberos', to: 'users#kerberos' , via: :post
    match '/filter', to: 'users#filter' , via: :post
  end
  match '/users' , to: 'users#update_groups', via: :put
  resources :users
  
  resources :audit_trail
  
  match 'summer_housing', to: 'summer_housing#summer_housing', via: :get
  match 'summer_housing/edit', to: 'summer_housing#summer_housing_edit', via: :get
  resources :summer_housing, path: "/summer_housing_application", as: "summer_apps"
  
  scope module: 'chapter' do
    resources :brothers
    
    match '/house', to: 'residences#house', via: :get
    match '/tour', to: 'residences#tour', via: :get
    scope '/residences' do 
      match '/room_picks', to: 'residences#room_picks', via: :get
      match '/room_picks', to: 'residences#mass_update', via: :post
    end
    resources :residences
    
    scope '/officers'  do
      match '/mass_update', to: 'officers#mass_edit', via: :get
      match '/mass_update', to: 'officers#mass_update', via: :post
      match '/update_contacts', to: 'officers#update_contacts', via: :post
    end
    
    match '/point_breakdown', to: 'house_points#full_breakdown', via: :get
    match 'house_points/reset', to: 'house_points#backup_and_clear', via: :post
    resources :officers do
      resources :house_points, shallow: true
    end
    
    match 'add_bible' , to: 'bibles#add_bible' , via: :get
    match 'add_bible' , to: 'bibles#new_bible' , via: :post
    match 'upload_bible' , to: 'bibles#upload_bible' , via: :post
  end
  
  namespace :backup do
    resources :house_point_tables
  end
  

end

app/views/chapter_public/house.html.erb
<% provide(:title , "The House")%>

<div class="row house">
	<h2>Welcome to the DKE House</h2>
	<div class="span6">
		<%= image_tag("dke_house.jpg", :alt => "")%>
	</div>
	<div class="span6">
		<h2>About the House</h2>
		<p>Work began on the DKE house in the fall of 1924. &nbsp; After 2 years of construction, the Sigma Tau chapter
			took posession of the new chapter house on Memorial Drive, where we have been located since.  </p>
		<br><h2><%= link_to "Tour the House", "#{root_path}house-tour"%></h2>
	</div>
</div>

app/views/chapter_public/letter.html.erb
<% provide(:title , @content.title)%>

<div class="row house">
	<div class="span12" align="left">
		<h2>
			<%= @content.title%>
			<%= link_to("Edit" , "#{chapter_public_path}/edit" , :class => "btn btn-primary pull-right") if @me.in_group(@content.user)%>
		</h2>
		<p><%= @content.content.gsub("\n","<br>").html_safe%></p>
	</div>	
</div>

app/views/chapter_public/president_letter.html.erb
<% provide(:title , @content.title)%>

<div class="row house">
	<div class="span12" align="left">
		<h2>
			<%= @content.title%>
			<%= link_to("Edit" , "#{chapter_public_path}/edit" , :class => "btn btn-primary pull-right") if @me.in_group(@content.user)%>
		</h2>
		<p><%= @content.content.gsub("\n","<br>").html_safe%></p>
	</div>	
</div>

app/views/chapter_public/room.html.erb
<% provide(:title , "The House: #{@room.name}")%>

<div class="row house">
	<h2><%= @room.name%></h2>
	<%= image_tag("house_img/#{@room.id}.jpg", :alt => "")%><br>
	<% if @room.capacity > 0%>
	  <b>Current Resident(s):</b>
	  <%= get_occupants(@room)%>
	<% end%>
</div>