config/routes.rb
DKESite::Application.routes.draw do
  root 'chapter/public_pages#home'

  get 'rush' => 'rush#index'

  match '/login' , to: 'chapter/public_pages#home' , via: :post
  match '/success' , to: 'application#success' , via: :get
  match '/loggedout' , to: 'application#loggedout' , via: :get
  
  match 'ch_passwd' , to: 'users#ch_passwd' , via: :get
  match 'ch_passwd' , to: 'users#set_passwd' , via: :patch
  
  scope '/users' do
    match '/add_pledges' , to: 'users#add_pledges' , via: :get
    match '/add_pledges' , to: 'users#create_pledges' , via: :post
    match '/query' , to: 'users#query' , via: :post
    match '/kerberos', to: 'users#kerberos' , via: :post
    match '/filter', to: 'users#filter' , via: :post
  end
  match '/users' , to: 'users#update_groups', via: :put
  resources :users
  
  resources :audit_trail
  
  match 'summer_housing', to: 'summer_housing#summer_housing', via: :get
  match 'summer_housing/edit', to: 'summer_housing#summer_housing_edit', via: :get
  resources :summer_housing, path: "/summer_housing_application", as: "summer_apps"
  
  scope module: 'chapter' do
    resources :brothers
    
    match '/house', to: 'residences#house', via: :get
    match '/tour', to: 'residences#tour', via: :get
    scope '/residences' do 
      match '/room_picks', to: 'residences#room_picks', via: :get
      match '/room_picks', to: 'residences#mass_update', via: :post
    end
    resources :residences
    
    scope '/officers'  do
      match '/mass_update', to: 'officers#mass_edit', via: :get
      match '/mass_update', to: 'officers#mass_update', via: :post
      match '/update_contacts', to: 'officers#update_contacts', via: :post
    end
    
    match '/point_breakdown', to: 'house_points#full_breakdown', via: :get
    match 'house_points/reset', to: 'house_points#backup_and_clear', via: :post
    resources :officers do
      resources :house_points, shallow: true
    end
    
    match 'add_bible' , to: 'bibles#add_bible' , via: :get
    match 'add_bible' , to: 'bibles#new_bible' , via: :post
    match 'upload_bible' , to: 'bibles#upload_bible' , via: :post
  end
  
  namespace :backup do
    resources :house_point_tables
  end
  

end

app/models/backup.rb
class Backup < ActiveRecord::Base
  self.abstract_class = true
  self.table_name_prefix = "backup_"
  establish_connection "backup_#{Rails.env}"
end

app/models/backup/house_point.rb
class Backup::HousePoint < Backup
  belongs_to :dke_info, class_name: "User::Brother::DkeInfo"
  belongs_to :officer, class_name: "Chapter::Officer"
  self.primary_key = "id"
  #id  int(11)
  #dke_info_id   int(11)
  #officer_id  int(11)
  #value   float
  #comment   varchar(255)
  #date  date
  
  def self.base_table_name
    return "backup_house_points"
  end
  
  def self.set_table_id(id)
    self.table_name = "#{self.base_table_name}_#{id}"
  end
  
  def self.breakdown
    breakdown = Hash.new
    self.select("dke_info_id").distinct.each do | per |
      if per.dke_info
        breakdown[per.dke_info_id] = {name: per.dke_info.brother.full_name,
                                      year: per.dke_info.brother.mit_info.year,
                                      points: Hash.new}
      end
    end
    self.select("*").order(officer_id: :asc).each do | entry |
      if breakdown.include? entry.dke_info_id
        officer = self.officers[entry.officer_id]
        if breakdown[entry.dke_info_id][:points].include? officer
          breakdown[entry.dke_info_id][:points][officer] << entry
        else
          breakdown[entry.dke_info_id][:points][officer] = [entry]
        end
      end
    end
    out = []
    breakdown.each do | key, value |
      out << value
    end
    return out.sort_by!{ |a| [a[:year], a[:name]]}
  end
  
  def self.officers
    officers = Hash.new
    self.select("officer_id").distinct.each do | entry |
      if entry.officer.nil?
        officers[entry.officer_id] = "unknown"
      else
        officers[entry.officer_id] =  entry.officer.name
      end
    end
    return officers
  end
  
  def self.restore_all
    #Check for unknown officers
    self.select("officer_id").distinct.each do |off|
      if off.officer.nil?
        self.where(officer_id: off.officer_id).each do | entry |
          entry.destroy
        end
      end
    end
    #Check for unknown brothers
    self.select("dke_info_id").distinct.each do | bro |
      if bro.dke_info.nil?
        self.where(dke_info_id: bro.dke_info_id).each do | entry |
          entry.destroy
        end
      end
    end
    origin = "#{Rails.configuration.database_configuration[Rails.env]['database']}.#{Chapter::HousePoint.table_name}"
    Backup::HousePoint.connection.execute("INSERT INTO #{origin} SELECT * from #{self.table_name}")
  end
  
  def self.destroy_all
    Backup::HousePoint.connection.execute("DROP TABLE #{self.table_name}")
  end
  
end

app/models/backup/house_point_table.rb
class Backup::HousePointTable < Backup
  #id  int(11)
  #start_date  date
  #end_date  date
  #created_at  datetime
  #updated_at  datetime
  
  def self.clear_and_backup
    return false if Chapter::HousePoint.count == 0
    entry = self.new
    entry.start_date = Chapter::HousePoint.minimum("created_at")
    entry.end_date = Chapter::HousePoint.maximum("updated_at")
    entry.save!
    table_name = "#{Backup::HousePoint.base_table_name}_#{entry.id}"
    origin = "#{Rails.configuration.database_configuration[Rails.env]['database']}.#{Chapter::HousePoint.table_name}"
    Backup::HousePoint.connection.execute("CREATE TABLE #{table_name} AS SELECT * from #{origin}")
    Chapter::HousePoint.destroy_all
    return true
  end
  
  def restore
    Backup::HousePointTable.clear_and_backup
    Backup::HousePoint.set_table_id(self.id)
    Backup::HousePoint.restore_all
    self.destroy
  end
  
  def destroy
    Backup::HousePoint.set_table_id(self.id)
    Backup::HousePoint.destroy_all
    super
  end
  
end

app/controllers/backup/house_point_tables_controller.rb
class Backup::HousePointTablesController < AuthenticationController
  before_action ->{holds?(["beta"])}
  
  def index
    @tables = Backup::HousePointTable.select("*")
  end
  
  def show
    @table = Backup::HousePointTable.find(params[:id])
    Backup::HousePoint.set_table_id(@table.id)
    @breakdown = Backup::HousePoint.breakdown
  end
  
  def destroy
    @table = Backup::HousePointTable.find(params[:id])
    @table.destroy
    flash[:success] = "House Point data destroyed"
    redirect_to backup_house_point_tables_path
  end
  
  def update
    @table = Backup::HousePointTable.find(params[:id])
    @table.restore
    flash[:success] = "House Point data restored"
    redirect_to backup_house_point_tables_path
  end
  
end

app/helpers/backup/house_point_tables_helper.rb
module Backup::HousePointTablesHelper
  
  def get_total(point_entries)
    total = 100
    point_entries.each do | pos, pos_entries|
      pos_entries.each do | entry |
        total += entry.value
       end
    end
    return total
  end
  
end

app/views/backup/house_point_tables/index.html.erb
<% provide(:title , 'Old House Point Data')%>

<div class="row">
	<div class="span12" align="left">
		<h3>Previuos House Point Data</h3>
	</div>
	<div class="span8 offset2">
	  <table class="table table-striped">
	  	<tr>
	  	  <th>Date Range</th>
	  	  <th>Actions</th>
	  	</tr>
	   <% @tables.each do | data |%>
	    <tr>
	      <td><%= humanize(data.start_date)%> - <%= humanize(data.end_date)%></td>
	      <td>
	      	<%= link_to "View", backup_house_point_table_path(data.id), class: "btn btn-default"%>
	      	<%= link_to("Restore" , backup_house_point_table_path(data.id) , method: :patch,
		  	  	data: { confirm: "Are you sure you like to restore all these entries?." },
		  	   	class: "btn btn-default") %>
	      	<!--<%= link_to("Delete" , backup_house_point_table_path(data.id) , method: :delete,
		  	  	data: { confirm: "Are you sure you like to delete all these entries? \n NOTE: This action can NOT be undone." },
		  	   	class: "btn btn-default") %>-->
	      </td>
	    </tr>
	   <% end %>
	  </table>
	</div>
</div>

app/views/backup/house_point_tables/show.html.erb
<% provide(:title , "House Points Breakdown #{humanize(@table.start_date)}")%>

<div class="row">
	<div class="span12" align="left" style="font-weight:bold;">
	  <h2>
	  	House Points Breakdown: <%= humanize(@table.start_date)%> - <%= humanize(@table.end_date)%>
	  	
      	<!--<%= link_to("Delete" , backup_house_point_table_path , method: :delete,
	  	  	data: { confirm: "Are you sure you like to delete all these entries? \n NOTE: This action can NOT be undone." },
	  	   	class: "btn btn-default pull-right") %>-->
	  	
	  	<%= link_to("Restore" , backup_house_point_table_path , method: :patch,
	  	  	data: { confirm: "Are you sure you like to restore all these entries?." },
	  	   	class: "btn btn-default pull-right") %>
	  </h2>
	</div>
	<table class="table table-striped">
	  <tr>
	  	<th>Name</th>
	  	<th>Year</th>
	  	<th>Entries</th>
	  </tr>
	  <% @breakdown.each do | brother | %>
	   <tr>
	  	<td><%= brother[:name]%></td>
	  	<td><%= brother[:year]%></td>
	  	<td>
	  	  <table class="table table-condensed">
	  	   <% brother[:points].each do | key, entries |%>
	  	    <% entries.each do | entry | %>
	  	  	  <tr>
	  	  	  	<td><%= key%></td>
	  	  	  	<td><%= entry.value%></td>
	  	  	  	<td><%= entry.comment%></td>
	  	  	  </tr>
	  	  	<% end %>
	  	   <% end %>
	  	  </table>
	  	  Total: <%= get_total(brother[:points])%>
	  	</td>
	   </tr>
	  <% end %>
	</table>
</div>